apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/talkrealm

namespace: talk-realm-dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: talk-realm

images:
  - name: talk-realm
    newTag: latest
