apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/redis
  - secret.yaml

namespace: talk-realm-dev

patches:
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: redis
