apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ./talk-realm
  - ./postgres
  - ./redis

namespace: talk-realm-dev

commonLabels:
  app.kubernetes.io/name: talkrealm
  app.kubernetes.io/namespace: talk-realm-dev
  prunable: "true"
